name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  dn42:
    name: Deploy to dn42
    runs-on: ubuntu-latest
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Cache Hugo Modules
        uses: actions/cache@v6
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Patch
        run: sed -i 's/50335033.xyz/blog.redearth.dn42/g' config/_default/hugo.toml

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: burnett01/rsync-deployments@v9
        with:
          switches: -avzr --delete
          path: public/
          remote_path: .
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
